---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-runner
  namespace: spack
  labels:
    srv: gitlab
    app: runner
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: gitlab
    srv: runner
