apiVersion: v1
kind: PersistentVolume
metadata:
  name: spack-postgresql
spec:
  storageClassName: us-east-1a
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://us-east-1a/vol-0c93a1d75e1221bdd
