---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: spack
  labels:
    app: gitlab
    svc: db
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: gitlab
    svc: db
