---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: spack
  labels:
    app: gitlab
    srv: db
spec:
  selector:
    matchLabels:
      app: gitlab
      srv: db
  serviceName: postgresql
  template:
    metadata:
      labels:
        app: gitlab
        srv: db
    spec:
      containers:
      - name: postgresql
        image: "postgres:9.6.2"
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab-db-user
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab-db-user
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab-db-name
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab-db-password
        - name: POD_IP
          valueFrom: { fieldRef: { fieldPath: status.podIP } }
        ports:
        - name: postgresql
          containerPort: 5432
        livenessProbe:
          exec:
            command: ["sh", "-c", "exec pg_isready --host $POD_IP"]
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command: ["sh", "-c", "exec pg_isready --host $POD_IP"]
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
        volumeMounts:
        - name: postgresql-vol-data
          mountPath: /var/lib/postgresql/data/pgdata
          subPath: postgresql-db
      nodeSelector:
        "beta.kubernetes.io/instance-type": "t2.medium"
  volumeClaimTemplates:
  - metadata:
      name: postgresql-vol-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 200Gi
