---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  chart:
    name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 19.2.2
  values:
    namespaceOverride: monitoring
    alertmanager:
      ingress:
        enabled: true
        hosts:
        - alertmanager.spack.io
        tls:
          - secretName: tls-alertmanager-webservice
            hosts:
              - alertmanager.spack.io
    grafana:
      ingress:
        enabled: true
        hosts:
        - grafana.spack.io
        tls:
          - secretName: tls-grafana-webservice
            hosts:
              - grafana.spack.io

    prometheus:
      ingress:
        enabled: true
        hosts:
        - prometheus.spack.io
        tls:
          - secretName: tls-prometheus-webservice
            hosts:
              - prometheus.spack.io
      prometheusSpec:
        nodeSelector:
          spack.io/node-pool: beefy
