---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  chart:
    name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 19.2.2
  values:
    namespaceOverride: monitoring
    alertmanager:
      ingress:
        enabled: false
      alertmanagerSpec:
        alertmanagerConfigSelector:
          matchLabels:
            alertmanagerConfig: spack

    grafana:
      ingress:
        enabled: false

    prometheus:
      ingress:
        enabled: false
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: gp2
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 200Gi
        nodeSelector:
          spack.io/node-pool: beefy
