---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-spack-io-redirect
  namespace: spack
  labels:
    app: s3-spack-io
    svc: web-redirect
spec:
  selector:
    matchLabels:
      app: s3-spack-io
      svc: web-redirect
  replicas: 2
  template:
    metadata:
      labels:
        app: s3-spack-io
        svc: web-redirect
    spec:
      containers:
      - name: web
        image: "schmunk42/nginx-redirect"
        imagePullPolicy: Always
        env:
        - name: SERVER_REDIRECT
          value: "spack-public.s3.amazonaws.com"
        ports:
        - name: http
          containerPort: 80
      nodeSelector:
        "beta.kubernetes.io/instance-type": "t2.medium"
