apiVersion: batch/v1
kind: CronJob
metadata:
  name: opensearch-index-build-logs
  namespace: custom
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: opensearch-index-build-logs
            image: ghcr.io/spack/opensearch-index-build-logs:0.0.1
            imagePullPolicy: IfNotPresent
            env:
            - name: OPENSEARCH_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: opensearch-index-build-logs
                  key: opensearch-endpoint
            - name: OPENSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: opensearch-index-build-logs
                  key: opensearch-username
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opensearch-index-build-logs
                  key: opensearch-password
          nodeSelector:
            spack.io/node-pool: base
