# NOTE(opadron): This file is only an example secrets file.  Do not use these
#                secrets in production!
---
apiVersion: v1
kind: Secret
metadata:
  name: cdash-secrets
  namespace: spack
type: Opaque
data:
  cdash-root-password: Y2Rhc2gtcm9vdC1zZWNyZXQ=

  cdash-db-host: bXlzcWw=
  cdash-db-type: bXlzcWw=
  cdash-db-name: Y2Rhc2g=
  cdash-db-login: Y2Rhc2gtbXlzcWw=
  cdash-db-port: ''
  cdash-db-pass: bXlzcWwtc2VjcmV0
