---
apiVersion: v1
kind: ConfigMap
metadata:
  name: runner-staging-patch
  namespace: gitlab
  annotations:
    cd.spack.io/staged-resource: "1"
data:
  apiVersion: helm.fluxcd.io/v1
  kind: HelmRelease
  name: runner-xlarge-x86-pub
  patch: |
    - op: replace
      path: /metadata/name
      value: runner-{ENV}
    - op: replace
      path: /spec/chart/version
      value: "0.37.2"  # bleeding edge
    - op: replace
      path: /spec/releaseName
      value: runner-{ENV}
    - op: replace
      path: /spec/values/gitlabUrl
      value: "https://gitlab.{ENV}.spack.io/"
    - op: replace
      path: /spec/values/terminationGracePeriodSeconds
      value: 300  # five minutes
    - op: replace
      path: /spec/values/concurrent
      value: 3
    - op: replace
      path: /spec/values/checkInterval
      value: 1
    - op: replace
      path: /spec/values/runners/tags
      value: "x86_64,avx,avx2,avx512,{ENV},public,aws,spack"
    - op: replace
      path: /spec/values/runners/secret
      value: gitlab-{ENV}-gitlab-runner-secret
    - op: replace
      path: /spec/values/runners/config
      value: |
          [[runners]]
          requestConcurrency =  3
          output_limit = 4096
          environment = ["FF_GITLAB_REGISTRY_HELPER_IMAGE=1"]
          [runners.kubernetes]
            privileged = false
            cpu_request = "9000m"
            namespace = "gitlab"
            pollTimeout = 600  # ten minutes
            service_account = "runner"
            [runners.kubernetes.node_selector]
              "kubernetes.io/arch" = "amd64"
              "spack.io/node-pool" = "glr-xlarge-pub"
