---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glciy-worker-centos
  namespace: spack
  labels:
    app: glciy
    svc: worker
    component: worker
    variant: centos
spec:
  selector:
    matchLabels:
      app: glciy
      svc: worker
      component: worker
      variant: centos
  replicas: 3
  template:
    metadata:
      labels:
        app: glciy
        svc: worker
        component: worker
        variant: centos
    spec:
      containers:
      - name: worker
        image: "opadron/glciy-worker-centos"
        imagePullPolicy: Always
        args: [
          "--queue-dir" , "/queue",
          "--cache-dir" , "/cache",
          "--remote"    , "git://github.com/scottwittenburg/spack",
          "--notify-url", "http://glciy-worker-centos"]
        volumeMounts:
        - name: glciy
          mountPath: /queue
          subPath: queue
        - name: glciy
          mountPath: /cache
          subPath: cache
      nodeSelector:
        "beta.kubernetes.io/instance-type": "t2.medium"
      volumes:
        - name: glciy
          persistentVolumeClaim:
            claimName: glciy-centos

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glciy-web-centos
  namespace: spack
  labels:
    app: glciy
    svc: worker
    component: web
    variant: centos
spec:
  selector:
    matchLabels:
      app: glciy
      svc: worker
      component: web
      variant: centos
  replicas: 1
  template:
    metadata:
      labels:
        app: glciy
        svc: worker
        component: web
        variant: centos
    spec:
      initContainers:
        - name: setup
          image: busybox
          imagePullPolicy: Always
          command: ["mkdir", "-p"]
          args: ["/import/dummy"]
          volumeMounts:
          - name: glciy
            mountPath: /import
      containers:
      - name: web
        image: "opadron/dws"
        imagePullPolicy: Always
        args: [
          "--queue-dir", "/queue",
          "--cache-dir", "/cache",
          "--bind",      "0.0.0.0",
          "--port",      "8080"]
        volumeMounts:
        - name: glciy
          mountPath: /queue
          subPath: queue
        - name: glciy
          mountPath: /cache
          subPath: cache
        ports:
        - name: http
          containerPort: 8080
      - name: cache-manager
        image: "opadron/scm"
        imagePullPolicy: Always
        args: [
          "--ttl", "300", "--size-limit",   "1M", "/queue",
          "--ttl", "900", "--size-limit", "900M", "/cache",
          "--node-limit", "1", "/dummy"]
        volumeMounts:
        - name: glciy
          mountPath: /queue
          subPath: queue
        - name: glciy
          mountPath: /cache
          subPath: cache
        - name: glciy
          mountPath: /dummy
          subPath: dummy
      # NOTE(opadron): Ensure that the cache manager sleeps
      #                for no longer than five minutes.
      - name: clock
        image: "busybox"
        imagePullPolicy: Always
        command: ["sh", "-c"]
        args: ["while sleep 300 ; do mktemp -p /dummy ; done"]
        volumeMounts:
        - name: glciy
          mountPath: /dummy
          subPath: dummy
      nodeSelector:
        "beta.kubernetes.io/instance-type": "t2.medium"
      volumes:
        - name: glciy
          persistentVolumeClaim:
            claimName: glciy-centos
