---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glciy-centos
  namespace: spack
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: spack-nfs
