---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm
  namespace: spack
spec:
  version: 7.6.2
  count: 1
  elasticsearchRef:
    name: elastic-search
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: ClusterIP
