---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-kibana
  namespace: spack
spec:
  secretName: tls-kibana
  issuerRef:
    name: letsencrypt
    kind: Issuer
  dnsNames:
  - kibana.spack.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - kibana.spack.io
