---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-search
  namespace: spack
spec:
  version: 7.6.2
  nodeSets:
    - name: master
      count: 3
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              readinessProbe:
                exec:
                  command:
                    - bash
                    - -c
                    - /mnt/elastic-internal/scripts/readiness-probe-script.sh
                  failureThreshold: 3
                  initialDelaySeconds: 10
                  periodSeconds: 12
                  successThreshold: 1
                  timeoutSeconds: 12
              env:
                - name: READINESS_PROBE_TIMEOUT
                  value: '10'
                - name: ES_JAVA_OPTS
                  value: "-Xms1g -Xmx1g"
              resources:
                requests:
                  memory: 2Gi
                  cpu: 1.7
                limits:
                  memory: 3.5Gi
                  cpu: 2.0
        nodeSelector:
          "beta.kubernetes.io/instance-type": "t3.medium"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 64Gi
            storageClassName: us-east-1a-scratch
    # - name: data
    #   count: 10
    #   config:
    #     node.master: false
    #     node.data: true
    #     node.ingest: true
    #     node.ml: true
    #     cluster.remote.connect: false
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: ClusterIP
