---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: spack
spec:
  version: 7.6.2
  count: 1
  elasticsearchRef:
    name: elastic-search
  podTemplate:
    spec:
      nodeSelector:
        "beta.kubernetes.io/instance-type": "t2.medium"
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: ClusterIP
