---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: gitlab-runner
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "watch", "list", "update", "create", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: gitlab-runner
subjects:
- kind: ServiceAccount
  name: gitlab-runner
roleRef:
  kind: Role
  name: gitlab-runner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-runner
  labels:
    app: gitlab-runner
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: gitlab
    srv: runner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner
  labels:
    app: gitlab
    srv: runner
spec:
  selector:
    matchLabels:
      app: gitlab
      srv: runner
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab
        srv: runner
    spec:
      serviceAccountName: gitlab-runner
      containers:
      - name: runner
        image: "gitlab/gitlab-runner:latest"
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - >
                export RUNNER_NAME="$( hostname )" ;
                gitlab-runner register \
                    --kubernetes-service-account gitlab-runner \
                    --tag-list docker,kubernetes

          preStop:
            exec:
              command: ["gitlab-runner", "unregister"]

        env:
        - name: DOCKER_IMAGE
          value: "ubuntu:latest"

        - name: CI_SERVER_URL
          value: "http://gitlab"

        - name: REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab-runner-token

        - name: RUNNER_EXECUTOR
          value: kubernetes

        - name: REGISTER_NON_INTERACTIVE
          value: "true"
