apiVersion: v1
kind: PersistentVolume
metadata:
  name: spack-mysql
spec:
  storageClassName: us-east-1a
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://us-east-1a/vol-09f639c87f3def4bd
