---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: spack
  labels:
    app: cdash
    svc: db
spec:
  type: ClusterIP
  ports:
  - name: database
    port: 3306
    targetPort: 3306
  selector:
    app: cdash
    svc: db
