    export GITLAB_SSH_KEY_BASE64="$( base64 < /secrets/gitlab-ssh-key )"
    export GITHUB_TOKEN="$( cat /secrets/github-access-token )"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gh-gl-sync
  namespace: spack
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: sync
            image: zackgalbreath/spack-ci-bridge:0.0.1
            imagePullPolicy: IfNotPresent
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gh-gl-sync
                  key: github-access-token
            - name: GITLAB_SSH_KEY
              valueFrom:
                secretKeyRef:
                  name: gh-gl-sync
                  key: gitlab-ssh-key
            args:
              - "scottwittenburg/gitlab-ci-tests"
              - "ssh://git@ssh.gitlab.spack.io/scott/gitlab-ci-tests"
              - "https://gitlab.spack.io"
              - "scott/gitlab-ci-tests"
          nodeSelector:
            "beta.kubernetes.io/instance-type": "t2.medium"
