---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gh-gl-sync
  namespace: spack
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: sync
            image: alpine
            imagePullPolicy: IfNotPresent
            command: ["sh", "/scripts/entrypoint.sh"]
            volumeMounts:
              - name: scripts
                mountPath: "/scripts"
              - name: secrets
                mountPath: "/secrets"
          volumes:
            - name: scripts
              configMap:
                name: gh-gl-sync
                defaultMode: 0700
            - name: secrets
              secret:
                secretName: gh-gl-sync
                defaultMode: 0700
          nodeSelector:
            "beta.kubernetes.io/instance-type": "t2.medium"
