# NOTE(opadron): This file is only an example secrets file.  Do not use these
#                secrets in production!
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets
  namespace: spack
type: Opaque
data:
  gitlab-root-password: Z2l0bGFiLXJvb3Qtc2VjcmV0
  gitlab-runner-token: cnVubmVyLXNlY3JldA==

  gitlab-db-host: cG9zdGdyZXNxbA==
  gitlab-db-name: Z2l0bGFi
  gitlab-db-user: Z2l0bGFi
  gitlab-db-password: cG9zdGdyZXMtc2VjcmV0

  gitlab-cache-host: cmVkaXMtbWFzdGVy
  gitlab-cache-password: cmVkaXMtc2VjcmV0
