---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-provisioner-data
  namespace: nfs-provisioner
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: us-east-1a
