---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: production
  namespace: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: user@example.com
    privateKeySecretRef:
      name: production
    dns01:
      providers:
      - name: aws-route53
        route53:
          accessKeyID: AKIAITFZKYLASKXPHVTQ
          secretAccessKeySecretRef:
            name: spack-aws-secret
            key: secret-key
