---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: spack
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: tgamblin@llnl.gov
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}

---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
  namespace: spack
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tgamblin@llnl.gov
    privateKeySecretRef:
      name: letsencrypt
    http01: {}
