---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-gitlab
  namespace: spack
spec:
  secretName: tls-gitlab
  issuerRef:
    name: letsencrypt
    kind: Issuer
  dnsNames:
  - gitlab.spack.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - gitlab.spack.io
