apiVersion: v1
kind: PersistentVolume
metadata:
  name: spack-gitlab
spec:
  storageClassName: us-east-1a
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://us-east-1a/vol-0b55fcd82511f36b5
