---
apiVersion: v1
kind: Service
metadata:
  name: spack-io
  labels:
    app: spack-io
    srv: web
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: spack-io
    srv: web

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spack-io-ingress
  labels:
    app: spack-io
    srv: ingress
spec:
  rules:
  - host: sp0ck.io
    http:
      paths:
      - backend:
          serviceName: spack-io
          servicePort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spack-io
  labels:
    app: spack-io
    srv: web
spec:
  selector:
    matchLabels:
      app: spack-io
      srv: web
  replicas: 2
  template:
    metadata:
      labels:
        app: spack-io
        srv: web
    spec:
      containers:
      - name: web
        image: "spack/spack.io:latest"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
