---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-packages
spec:
  secretName: tls-packages
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - packages.next.spack.io
