---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-webservice
  namespace: gitlab
  annotations:
    fluxcd.io/ignore: "true"
spec:
  secretName: tls-gitlab-webservice
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - gitlab.next.spack.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-registry
  namespace: gitlab
  annotations:
    fluxcd.io/ignore: "true"
spec:
  secretName: tls-gitlab-registry
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - registry.next.spack.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-minio
  namespace: gitlab
  annotations:
    fluxcd.io/ignore: "true"
spec:
  secretName: tls-gitlab-minio
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - minio.next.spack.io
