---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  releaseName: gitlab
  chart:
    name: gitlab
    repository: https://charts.gitlab.io
    version: 4.8.8 # gitlab@13.8.8

  values:
    nodeSelector:
      spack.io/node-pool: gitlab

    global:
      common:
        labels: {}

      operator:
        enabled: false

      edition: ee

      hosts:
        domain: spack.io
        https: true
        gitlab:
          name: gitlab.spack.io
        minio:
          name: minio.gitlab.spack.io
        registry:
          name: registry.gitlab.spack.io
        smartcard:
          enabled: false
        ssh: ssh.gitlab.spack.io

      ingress:
        configureCertmanager: false
        class: nginx

      gitlab:
        license: {}

      initialRootPassword: {}

      psql:
        connectTimeout:
        password: {}

      redis:
        password:
          enabled: true

      minio:
        enabled: true

      grafana:
        enabled: false

      appConfig:
        smartcard:
          enabled: false

      antiAffinity: hard
    ### END OF GLOBAL SECTION

    certmanager:
      install: false

    prometheus:
      install: false

    nginx-ingress:
      enabled: false

    minio:
      ingress:
        tls:
          secretName: tls-gitlab-minio
      nodeSelector:
        spack.io/node-pool: gitlab
      persistence:
        size: 100Gi

    registry:
      ingress:
        tls:
          secretName: tls-gitlab-registry
      nodeSelector:
        spack.io/node-pool: gitlab

    gitlab-runner:
      install: false

    gitlab:
      ingress:
        tls:
          enabled: true
      webservice:
        ingress:
          enabled: true
          tls:
            enabled: true
            secretName: tls-gitlab-webservice
        minReplicas: 2
        maxReplicas: 4
        nodeSelector:
          spack.io/node-pool: gitlab

      gitlab-exporter:
        nodeSelector:
          spack.io/node-pool: gitlab

      gitlab-shell:
        service:
          type: LoadBalancer
        nodeSelector:
          spack.io/node-pool: gitlab

      sidekiq:
        nodeSelector:
          spack.io/node-pool: gitlab

      task-runner:
        nodeSelector:
          spack.io/node-pool: gitlab

        replicas: 4
        antiAffinityLabels:
          matchLabels:
            app: 'gitaly'

      gitaly:
        nodeSelector:
          spack.io/node-pool: gitlab

      migrations:
        nodeSelector:
          spack.io/node-pool: gitlab
