---
# Provisioner for normal gitlab runners
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  providerRef:
    name: default

  # Consolidation will de-provision larger than necessary nodes
  consolidation:
    enabled: true

  # Resource limits for this provisioner only
  limits:
    resources:
      cpu: 5k
      memory: 20Ti

  requirements:
    # Only spin up arm64 and amd64 nodes
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64", "amd64"]

    # Don't provision nodes from certain instance families.
    - key: "karpenter.k8s.aws/instance-family"
      operator: NotIn
      values:
        # too old (nehalem)
        - "m2"
        - "t1"

        # too old (westmere)
        - "c1"
        - "m1"

        # too old (ivybridge)
        - "c3"
        - "g2"
        - "i2"
        - "m3"
        - "r3"

        # too big / expensive
        - "cc2"
        - "mac1"
        - "mac2"
        - "p3dn"
        - "p4d"
        - "x1"
        - "x2idn"
        - "u-12tb1"
        - "u-18tb1"
        - "u-3tb1"
        - "u-6tb1"
        - "u-9tb1"

    # Availability Zones
    - key: "topology.kubernetes.io/zone"
      operator: In
      values:
        - "us-east-1a"
        - "us-east-1b"
        - "us-east-1c"
        - "us-east-1d"

    # Try spot, fall over to on-demand
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]

  # Only provision nodes from the glr-large-pub node pool
  labels:
    spack.io/node-pool: glr-large-pub

---
# Provisioner for testing gitlab runners
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: testing
spec:
  providerRef:
    name: default

  # Consolidation will de-provision larger than necessary nodes
  consolidation:
    enabled: true

  requirements:
    # Only spin up arm64 nodes
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64", "amd64"]

    # Availability Zones
    - key: "topology.kubernetes.io/zone"
      operator: In
      values:
        - "us-east-1a"
        - "us-east-1b"
        - "us-east-1c"
        - "us-east-1d"

    # Allowed instance types
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - "m6g.4xlarge" # ARM64 instances
        - "m5zn.3xlarge" # AMD64 instances

    # Try spot, fall over to on-demand
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]

  # Only provision nodes from the glr-large-testing-pub node pool
  labels:
    spack.io/node-pool: glr-large-testing-pub
