apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  # Terminate nodes after 30 seconds of idle time
  ttlSecondsAfterEmpty: 30
  providerRef:
    name: default
  requirements:
    # Only spin up arm64 nodes
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64"]

    # Availability Zones
    - key: "topology.kubernetes.io/zone"
      operator: In
      values:
        - "us-east-1a"
        - "us-east-1b"
        - "us-east-1c"
        - "us-east-1d"

    # Allowed instance types
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["m6g.4xlarge"]

    # Try spot, fall over to on-demand
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
  labels:
    spack.io/node-pool: glr-large-testing-pub
