---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-glciy
  namespace: spack
spec:
  secretName: tls-glciy
  issuerRef:
    name: letsencrypt
    kind: Issuer
  dnsNames:
  - internal.spack.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - internal.spack.io
