---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  rules:
  - host: gitlab.cluster.local
    # https:
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: http
