---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-www
  namespace: spack
spec:
  secretName: tls-www
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: spack.io
  dnsNames:
  - spack.io
  - www.spack.io
