---
apiVersion: v1
kind: Service
metadata:
  name: glciy-worker-ubuntu
  namespace: spack
  labels:
    app: glciy
    svc: worker
    component: web
    variant: ubuntu
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: glciy
    svc: worker
    component: web
    variant: ubuntu
