---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-ro-postgresql-password
  namespace: gitlab
  annotations:
      fluxcd.io/ignore: "true"
data:
  postgresql-gitlab-ro-user-password: DEADBEEF # fake-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: metabase-postgresql-password
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: "true"
data:
  postgresql-password: DEADBEEF # fake-secret
