name: Publish Docker Images

on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker-image:
          - gh-gl-sync
          - gitlab-api-scrape
          - ci-key-rotate
          - ci-key-clear
          - gitlab-webservice
          - gitlab-sidekiq
          - gitlab-toolbox
          - gitops
          - gitlab-stuckpods
          - gitlab-clear-pipelines
          - notary
          - python-aws-bash
        include:
          - docker-image: gh-gl-sync
            image-tags: ghcr.io/spack/ci-bridge:0.0.28
          - docker-image: gitlab-api-scrape
            image-tags: ghcr.io/spack/gitlab-api-scrape:0.0.2
          - docker-image: ci-key-rotate
            image-tags: ghcr.io/spack/ci-key-rotate:0.0.2
          - docker-image: ci-key-clear
            image-tags: ghcr.io/spack/ci-key-clear:0.0.1
          - docker-image: gitlab-webservice
            image-tags: ghcr.io/spack/gitlab-webservice:v14.6.3
          - docker-image: gitlab-sidekiq
            image-tags: ghcr.io/spack/gitlab-sidekiq:v14.6.3
          - docker-image: gitlab-toolbox
            image-tags: ghcr.io/spack/gitlab-toolbox:v14.6.3
          - docker-image: gitops
            image-tags: ghcr.io/spack/gitops:0.0.4
          - docker-image: gitlab-stuckpods
            image-tags: ghcr.io/spack/stuckpods:0.0.1
          - docker-image: gitlab-clear-pipelines
            image-tags: ghcr.io/spack/gitlab-clear-pipelines:0.0.1
          - docker-image: notary
            image-tags: ghcr.io/spack/notary:latest
          - docker-image: python-aws-bash
            image-tags: ghcr.io/spack/python-aws-bash:0.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.docker-image }}
        id: docker-build-push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./images/${{ matrix.docker-image }}
          file: ./images/${{ matrix.docker-image }}/Dockerfile
          push: true
          tags: ${{ matrix.image-tags }}

      - name: Image digest
        run: echo ${{ steps.docker-build-push.outputs.digest }}
