name: Publish Docker Images

on:
  push:
    branches: main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push ci-bridge
        id: docker_build_sync
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./images/gh-gl-sync
          file: ./images/gh-gl-sync/Dockerfile
          push: true
          tags: ghcr.io/spack/ci-bridge:0.0.24
      -
        name: Image digest
        run: echo ${{ steps.docker_build_sync.outputs.digest }}
  scrape:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push gitlab-api-scrape
        id: docker_build_scrape
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./images/gitlab-api-scrape
          file: ./images/gitlab-api-scrape/Dockerfile
          push: true
          tags: ghcr.io/spack/gitlab-api-scrape:0.0.2
      -
        name: Image digest
        run: echo ${{ steps.docker_build_scrape.outputs.digest }}
  rotate-aws-keys:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push rotate-aws-keys
        id: docker_build_rotate_aws_keys
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./images/ci-key-rotate
          file: ./images/ci-key-rotate/Dockerfile
          push: true
          tags: ghcr.io/spack/ci-key-rotate:0.0.2
      -
        name: Image digest
        run: echo ${{ steps.docker_build_rotate_aws_keys.outputs.digest }}
  clear-admin-keys:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push clear-admin-keys
        id: docker_build_clear_admin_keys
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./images/ci-key-clear
          file: ./images/ci-key-clear/Dockerfile
          push: true
          tags: ghcr.io/spack/ci-key-clear:0.0.1
      -
        name: Image digest
        run: echo ${{ steps.docker_build_clear_admin_keys.outputs.digest }}
  gitlab-webservice:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push gitlab-webservice
        id: docker_build_gitlab_webservice
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./images/gitlab-webservice
          file: ./images/gitlab-webservice/Dockerfile
          push: true
          tags: ghcr.io/spack/gitlab-webservice:v14.4.1
      -
        name: Image digest
        run: echo ${{ steps.docker_build_gitlab_webservice.outputs.digest }}
  gitlab-sidekiq:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push gitlab-sidekiq
        id: docker_build_gitlab_sideqkiq
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./images/gitlab-sidekiq
          file: ./images/gitlab-sidekiq/Dockerfile
          push: true
          tags: ghcr.io/spack/gitlab-sidekiq:v14.4.1
      -
        name: Image digest
        run: echo ${{ steps.docker_build_gitlab_sideqkiq.outputs.digest }}
  gitlab-task-runner:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push gitlab-task-runner
        id: docker_build_gitlab_task_runner
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./images/gitlab-task-runner
          file: ./images/gitlab-task-runner/Dockerfile
          push: true
          tags: ghcr.io/spack/gitlab-task-runner:v14.4.1
      -
        name: Image digest
        run: echo ${{ steps.docker_build_gitlab_task_runner.outputs.digest }}
  gitops:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push gitops
        id: docker_build_gitops
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./images/gitops
          file: ./images/gitops/Dockerfile
          push: true
          tags: ghcr.io/spack/gitops:0.0.4
      -
        name: Image digest
        run: echo ${{ steps.docker_build_gitops.outputs.digest }}
