name: Publish Docker Images

on:
  push:
    branches: main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ci-bridge
        id: docker_build_sync
        uses: docker/build-push-action@v2
        with:
          context: ./images/gh-gl-sync
          file: ./images/gh-gl-sync/Dockerfile
          push: true
          tags: spack/ci-bridge:0.0.21
      -
        name: Image digest
        run: echo ${{ steps.docker_build_sync.outputs.digest }}
  scrape:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push gitlab-api-scrape
        id: docker_build_scrape
        uses: docker/build-push-action@v2
        with:
          context: ./images/gitlab-api-scrape
          file: ./images/gitlab-api-scrape/Dockerfile
          push: true
          tags: spack/gitlab-api-scrape:0.0.2
      -
        name: Image digest
        run: echo ${{ steps.docker_build_scrape.outputs.digest }}
  rotate-aws-keys:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push rotate-aws-keys
        id: docker_build_rotate_aws_keys
        uses: docker/build-push-action@v2
        with:
          context: ./images/ci-key-rotate
          file: ./images/ci-key-rotate/Dockerfile
          push: true
          tags: spack/ci-key-rotate:0.0.2
      -
        name: Image digest
        run: echo ${{ steps.docker_build_rotate_aws_keys.outputs.digest }}
  clear-admin-keys:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push clear-admin-keys
        id: docker_build_clear_admin_keys
        uses: docker/build-push-action@v2
        with:
          context: ./images/ci-key-clear
          file: ./images/ci-key-clear/Dockerfile
          push: true
          tags: spack/ci-key-clear:0.0.1
      -
        name: Image digest
        run: echo ${{ steps.docker_build_clear_admin_keys.outputs.digest }}
  gitlab-webservice:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push gitlab-webservice
        id: docker_build_gitlab_webservice
        uses: docker/build-push-action@v2
        with:
          context: ./images/gitlab-webservice
          file: ./images/gitlab-webservice/Dockerfile
          push: true
          tags: spack/gitlab-webservice:v13.8.8
      -
        name: Image digest
        run: echo ${{ steps.docker_build_gitlab_webservice.outputs.digest }}
  gitlab-sidekiq:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push gitlab-sidekiq
        id: docker_build_gitlab_sideqkiq
        uses: docker/build-push-action@v2
        with:
          context: ./images/gitlab-sidekiq
          file: ./images/gitlab-sidekiq/Dockerfile
          push: true
          tags: spack/gitlab-sidekiq:v13.8.8
      -
        name: Image digest
        run: echo ${{ steps.docker_build_gitlab_sideqkiq.outputs.digest }}
  gitlab-task-runner:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push gitlab-task-runner
        id: docker_build_gitlab_task_runner
        uses: docker/build-push-action@v2
        with:
          context: ./images/gitlab-task-runner
          file: ./images/gitlab-task-runner/Dockerfile
          push: true
          tags: spack/gitlab-task-runner:v13.8.8
      -
        name: Image digest
        run: echo ${{ steps.docker_build_gitlab_task_runner.outputs.digest }}
